# Generated by Django 4.1.3 on 2022-11-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("business", models.TextField(blank=True, null=True)),
                ("memo", models.TextField(blank=True, null=True)),
                ("hp_url", models.URLField(blank=True, null=True)),
                ("rikunabi_url", models.URLField(blank=True, null=True)),
                ("mainabi_url", models.URLField(blank=True, null=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("delete_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
